trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '*/**.csproj'
    configuration: Debug
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '*/**.Test.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: 'Fario.Extensions.Configuration/**.csproj'
    versioningScheme: 'off'
    packDirectory: '$(Build.ArtifactStagingDirectory)'
    configuration: 'Release'