trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: 'Fario.Extensions.Configuration/**.csproj'
    versioningScheme: 'off'
    configuration: 'Release'